<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: faith
 * Date: Sun, 03 May 2009 10:04:00 -0400
 */

$conf['savedir'] = '/www/urmp.org/support/data';
$conf['title'] = 'urmp: the ur music player';
$conf['template'] = 'urmp';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['registernotify'] = 'faith2009@alephnull.com';
$conf['disableactions'] = 'register';
$conf['sneaky_index'] = 1;
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['subscribers'] = 1;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['plugin']['captcha']['mode'] = 'image';
$conf['tpl']['urmp']['sidebar'] = 'both';
$conf['tpl']['urmp']['left_sidebar_content'] = 'main,user,group';
$conf['tpl']['urmp']['right_sidebar_content'] = 'user,group,namespace';
