- hosts: image
  vars_files:
    - passwords.yml
  vars:
    vm_installation: true
    using_devuan: true
    install_unstable: true
    install_local_time_source: true
    ntp0: 10.42.1.3
    ntp1: 10.42.1.33
    ntp2: 10.42.93.1
    ntp3: 10.42.0.2
    configured_port: 22

  tasks:
    - import_tasks: tasks/update_apt.yml
    - import_tasks: tasks/update_network_vm.yml
    - import_tasks: tasks/update_sudo.yml
    - import_tasks: tasks/update_distribution.yml
    - import_tasks: tasks/update_hostname.yml
    - import_tasks: tasks/update_chrony.yml
    - import_tasks: tasks/update_keymap.yml
    - import_tasks: tasks/update_sysctl_simple.yml
    - import_tasks: tasks/update_crontab.yml
    - import_tasks: tasks/update_bashrc.yml
    - import_tasks: tasks/update_dash.yml
    - import_tasks: tasks/update_ssh_remote_keys.yml
    - import_tasks: tasks/update_tools_general.yml
    - import_tasks: tasks/update_tools_guest_vm.yml
    - import_tasks: tasks/update_rsyncd.yml
    - import_tasks: tasks/update_user_login.yml
    - import_tasks: tasks/update_localization_vm.yml
    - import_tasks: tasks/update_grub.yml
    - import_tasks: tasks/update_virtiofs.yml
    - import_tasks: tasks/update_syslog.yml
    - import_tasks: tasks/update_cache.yml

    - name: Remove pcscd
      apt:
        name: pcscd
        state: absent

