---
- hosts: filer2
  gather_facts: no
  become: yes
  become_method: su
  environment:
    PATH: /sbin:/usr/sbin:"{{ ansible_env.PATH }}"
  vars_files:
    - default.yml
    - passwords.yml
  vars:
    - using_devuan: true
    - install_virt_tools: true
    - install_dual_boot: false
    - ntp_local: true
    - eth0_br0_network: true

  roles:
    - early
    - common
