---
- hosts: home2
  gather_facts: no
  become: yes
  become_method: su
  environment:
    PATH: /sbin:/usr/sbin:"{{ ansible_env.PATH }}"
  vars_files:
    - passwords.yml
  vars:
    - host_key_checking: false
    - install_faith: true
    - install_rpi: true
    - ntp_local: true

  roles:
    - early
    - rpi
    - common
