---
- hosts: puck-compute
  gather_facts: no
  become: yes
  become_method: su
  environment:
    PATH: /sbin:/usr/sbin:"{{ ansible_env.PATH }}"
  vars_files:
    - passwords.yml
  vars:
    - install_laptop_tools: true
    - install_laptop_ssh: true
    - install_x11_tools: false
    - install_x11_tools_ubuntu: true
    - install_intel_driver: false
    - install_nvidia_driver: false
    - install_virt_tools: true
    - ntp_anonymous: true
    - install_faith: true
    - install_rpi: false
    - install_dual_boot: false
    - using_debian: false
    - using_devuan: false
    - using_ubuntu: true
    - eth0_br0_network: false

  roles:
    - early
    - laptop
    - common
