# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 01 Feb 2008 18:33:14 -0500
*               @ALL          1
*               @user         8
