<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: faith
 * Date: Thu, 09 Jul 2009 20:23:48 -0400
 */

$conf['title'] = 'Hybrid Sky';
$conf['template'] = 'hybridsky';
$conf['showuseras'] = 'loginname';
$conf['tocminheads'] = '3';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['rememberme'] = 1;
$conf['registernotify'] = 'faith2009@alephnull.com';
$conf['disableactions'] = 'register';
$conf['sneaky_index'] = 1;
$conf['securecookie'] = 1;
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['subscribers'] = 1;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['rss_content'] = 'abstract';
$conf['xsendfile'] = '0';
$conf['plugin']['captcha']['mode'] = 'image';
$conf['savedir'] = '/www/hybridsky.org/support/data';
$conf['tpl']['hybridsky']['sidebar'] = 'both';
$conf['tpl']['hybridsky']['left_sidebar_content'] = 'main,user,group';
$conf['tpl']['hybridsky']['right_sidebar_content'] = 'user,group,namespace';

// end auto-generated content
