---
- name: Install Python tools
  apt:
    pkg:
      - mypy
      - python-is-python3
      - python3
      - python3-poetry
      - pylama
      - pylint
      - python3-click
      - python3-dateparser
      - python3-ephem
      - python3-keyring
      - python3-pylatex
      - python3-libtorrent
      - python3-opencv
      - python3-paramiko
      - python3-pip
      - python3-poetry
      - python3-protobuf
      - python3-pyotp
      - python3-pyzbar
      - python3-tesserocr

