---
- name: Disable statd
  lineinfile:
    dest: /etc/default/nfs-common
    regexp: NEED_STATD=
    line: NEED_STATD=false

- name: Enable idmapd
  lineinfile:
    dest: /etc/default/nfs-common
    regexp: NEED_IDMAPD=
    line: NEED_IDMAPD=true

- name: Disable gssd
  lineinfile:
    dest: /etc/default/nfs-common
    regexp: NEED_GSSD=
    line: NEED_GSSD=false
