---
- name: Use bash instead of dash for /bin/sh
  debconf: name=dash/sh
           question=dash/sh
           vtype=boolean
           value=false

- name: Reconfigure dash
  command: dpkg-reconfigure -f noninteractive dash

- name: Make sure /bin/sh is bash
  command: /bin/ln -sf bash sh
  args:
    chdir: /bin
