---
- name: Install DHCP networking
  copy:
    dest: /etc/network/interfaces
    content: |
      auto lo
      iface lo inet loopback

      allow-hotplug eth0
      iface eth0 inet dhcp

      allow-hotplug eth1
      iface eth1 inet dhcp
