---
- name: Update authorized_keys
  authorized_key: user='{{ item.user }}' key='{{ item.key }}' state=present
  with_items:
  - { user: 'root', 'key': "{{ default.authorized_key }}" }
  - { user: "{{ default.nonroot_user }}", 'key': "{{ default.authorized_key }}" }

- name: Update sshd_config
  lineinfile: path=/etc/ssh/sshd_config
              regexp='{{ item.regexp }}'
              line='{{ item.line }}'
  with_items:
    - { regexp: 'PermitRootLogin', line: 'PermitRootLogin prohibit-password' }
    - { regexp: 'Port', line: 'Port {{ configured_port}}' }
  register: statea

- name: Update remote security profile for sshd_config
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      PermitEmptyPasswords no
      Match Address *,!10.42.0.0/16,!127.0.0.1,!::1
        PermitRootLogin no
        PasswordAuthentication no
        AllowUsers {{ default.nonroot_user }}
  register: stateb

- name: Reload ssh
  sysvinit:
    name: ssh
    state: restarted
  when: statea.changed or stateb.changed

- name: Set ansible_port
  set_fact:
    ansible_port: "{{ configured_port }}"
