---
- name: Set hostname
  copy:
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'
    content: "{{ vm_hostname }}"

- name: Add local machine name to /etc/hosts
  lineinfile: path=/etc/hosts
              regexp='127.0.1.1'
              line='127.0.1.1       {{ vm_hostname }}.{{ default.domain }} {{ vm_hostname }}'
              state=present
              insertafter='127.0.0.1'
