---
- name: Add custom aliases and bindings to global /etc/bash.bashrc
  blockinfile:
    dest: /etc/bash.bashrc
    block: |
      unset LC_ALL
      export LANG=en_US.UTF-8
      export LC_TIME=C
      export LESS='diMfX'
      alias ls='ls -a'
      alias ll='ls -la'
      alias df='df -h'
      alias du='du -h'
      bind '"\M-p": history-search-backward'
      bind '"\ep": history-search-backward'
      bind '"\M-n": history-search-forward'
      bind '"\en": history-search-forward'
      HISTTIMEFORMAT="%F %T "
      HISTFILESIZE=1000000
      HISTSIZE=1000000
