<?php

/* 
 * Include this file to define the thumbnailreference function.
 * No output is generated by including this file.
 */

/*
 * This function generates the html to put a thumbnail on the current page.
 * Parameter size should be one of 0, 1, or 2 for small, medium, or large thumbnail.
 */

function thumbnailreference($picturename, $size)
{
	echo "<p><strong>Here I am in thumbnailreference</strong></p>";	
}

/*
 * This routine returns the full path name of the directory we are running in.
 * A trailing '/' is included just for convenience.
 */
function get_path()
{
	$info = pathinfo($_SERVER["PATH_TRANSLATED"]);
	$path = $info["dirname"] . "/";
	return $path;
}


?>