<?php

/* 
 * Include this file to define the thumbnailreference function.
 * No output is generated by including this file.
 */

/*
 * This function generates the html to put a thumbnail on the current page.
 * Parameter size should be one of 0, 1, or 2 for small, medium, or large thumbnail.
 */

function thumbnailreference($picturename, $size)
{
	/*$dir = get_path();
	$info = pathinfo($_ENV["REQUEST_URI"]);
	$medium = "/support/pixmedium.php?n=" . $picturename . "&d=" . $info["dirname"] . "/";
	echo "<table><tr><td colspan=\"2\">";
	echo "<a href=\"" . htmlspecialchars($medium) . "\">";
	echo "<img src=\"" . htmlspecialchars(get_pix($dir, $picturename, $size + 2)) ."\" border=\"0\">";
	echo "</a></td></tr>";
	echo "<tr><td><a href=\"" . htmlspecialchars($medium) . "\">" .
		"<font face=\"Arial, Helvetica, sans-serif\">Click to enlarge</font></a></td>";
	echo "<td><a href=\"" . htmlspecialchars(get_pix($dir, $picturename, 0)) .
		"\"><font face=\"Arial, Helvetica, sans-serif\">Full size image</font></a></td></tr></table>";
	*/
	echo "<p><strong>Here I am</strong></p>";	
}

/*
 * This routine returns the full path name of the directory we are running in.
 * A trailing '/' is included just for convenience.
 */
function get_path()
{
	$info = pathinfo($_ENV["REQUEST_URI"]);
	$path = $_ENV["DOCUMENT_ROOT"] . $info["dirname"] . "/";
	return $path;
}

/*
 * This routine creates and manages the image cache.
 *
 * get_pix($dir, $image_name, $size)
 *    Returns a relative path to the image.
 *    Usage:
 *		<img src="<?php htmlspecialchars(get_pix(get_path(), "dscn0086", 2)) ?>">
 *    or
 *		$file = get_path() . get_pix(get_path(), "dsn0086", 2);
 *
 *
 * Parameters:
 *
 * $image_name
 *   This is the name of the image file.  The suffice .jpg or .JPG will be added
 *   as necessary.  Case insensitive.
 *
 * $size
 *   Five sizes are defined.
 *    0 = use the original large image
 *    1 = use a medium sized (800 pixel) image
 *    2 = small thumbnail
 *    3 = medium thumbnail
 *    4 = large thumbnail
 *
 * Medium sized images are 800 pixels in their largest dimension, unless the source image
 * is no more than 1024 pixels in either dimension.
 *
 * If the source image is no more than 1024 pixels in either dimension then the source
 * image is used as the medium image.
 *
 * All errors are thrown to the user, none are returned.
 *
 * KNOWN ISSUES:
 *  - The thumbnails are cached in the "pixsmall" directory.  If the picture is found
 *    in the cache, it is used, regardless of whether it matches the requested size.
 */

function get_pix($dir, $image_name, $size)
{
	$largedir = "pixlarge/";
	$thumbdir = "pixsmall/";

	// Find the source file.  Required to exist even if we do not need it.
	$thumb_imagename = $source_imagename = strtolower($image_name) . ".jpg";
	$found = false;
	
	if (is_dir($dir . $largedir) && ($dh = opendir($dir . $largedir))) {
		while (($file = readdir($dh)) !== false) {
			if ($source_imagename == strtolower($file)) {
				$found = true;
				/* Use the actual case version of the name */
				$source_imagename = $file;
				break;
			}
		}
		closedir($dh);
	} else
		trigger_error("Cannot open directory \"" . $dir . $largedir . "\" for reading.", E_USER_ERROR);

	if ($found == false)
		trigger_error("cannot find source image \"" . $source_imagename . "\" in directory \"" . $dir . $largedir . "\"", E_USER_ERROR);

	$source_full_name = $largedir . $source_imagename;

	if ($size == 0)
		// just use the original large image
		return $source_full_name;

	$medium = false;
	if ($size == 2)
		$size = 64;
	elseif ($size == 3)
		$size = 128;
	elseif ($size == 4)
		$size = 256;
	else {
		$size = 800;
		$medium = true;
	}

	if ($medium)
		$thumbdir = "pixmedium/";

	/*
	 * Find out if a cached version of the image we need exists.
	 * If it does not, create it.
	 */
	$thumb_full_name = $thumbdir . $thumb_imagename;
	if (!file_exists($dir . $thumb_full_name)) {
		if (false !== (list($ws, $hs) = @getimagesize($dir . $source_full_name))) {
			if ($ws > $hs) {
				$ratio = ((float)$size) / $ws;
			} else {
				$ratio = ((float)$size) / $hs;
			}
		} else
			trigger_error("Cannot read source image file \"" . $dir . $source_full_name . "\"", E_USER_ERROR);

		$wt = $ws * $ratio;
		$ht = $hs * $ratio;
		$thumb = imagecreatetruecolor($wt,$ht);
		$source = imagecreatefromjpeg($dir . $source_full_name);
		if ("" == $source)
			trigger_error("image create from jpeg failed", E_USER_ERROR);
	
		imagecopyresampled($thumb,$source,0,0,0,0,$wt,$ht,$ws,$hs);
		imagejpeg($thumb, $dir . $thumb_full_name);
		imagedestroy($source);
		imagedestroy($thumb);
	}
	
	return $thumb_full_name;
}
?>