Section "ServerLayout"
	Identifier     "X.org Configured"
	Screen      0  "Screen0" 0 0
	Screen	       "Screen2" LeftOf "Screen0"
EndSection

Section "ServerFlags"
	Option "AllowEmptyInput" "false"
	#Option "AutoAddDevices" "false"
	Option "DontZap" "false"
EndSection

Section "Files"
	ModulePath   "/usr/lib/xorg/modules"
	FontPath     "/usr/share/fonts/X11/misc"
	FontPath     "/usr/share/fonts/X11/cyrillic"
	FontPath     "/usr/share/fonts/X11/100dpi/:unscaled"
	FontPath     "/usr/share/fonts/X11/75dpi/:unscaled"
	FontPath     "/usr/share/fonts/X11/Type1"
	FontPath     "/usr/share/fonts/X11/100dpi"
	FontPath     "/usr/share/fonts/X11/75dpi"
	FontPath     "/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType"
	FontPath     "built-ins"
EndSection

Section "Module"
	disable "dri"
	Load  "record"
	Load  "extmod"
	Load  "dbe"
	Load  "glx"
	Load  "xtrap"
EndSection

Section "Monitor"
	#DisplaySize	  410   310	# mm
	Identifier   "Monitor0"
	VendorName   "DEL"
	ModelName    "DELL 2001FP"
	Option	    "DPMS"
EndSection

Section "Monitor"
	#DisplaySize	  410   310	# mm
	Identifier   "Monitor1"
	VendorName   "NEC"
	ModelName    "LCD2070VC"
	Option	    "DPMS"
	Option	     "RightOf" "Monitor0"
EndSection

Section "Monitor"
	#DisplaySize	  410   310	# mm
	Identifier   "Monitor2"
	VendorName   "Sony"
	ModelName    "Unknown"
	Option	     "DPMS"
EndSection

Section "Device"
	Identifier  "Card0"
	Driver      "radeon"
	VendorName  "ATI Technologies Inc"
	BoardName   "RV370 [Sapphire X550 Silent]"
	BusID       "PCI:1:0:0"
	Screen 0
	Option       "monitor-DVI-0" "Monitor0"
	Option       "monitor-DVI-1" "Monitor1"
	Option "AccelMethod" "XAA"
EndSection

Section "Device"
	Identifier  "Card2"
	Driver      "radeon"
	VendorName  "ATI Technologies Inc"
	BoardName   "RV100 QY [Radeon 7000/VE]"
	BusID       "PCI:17:10:0"
	Screen 0
	Option "BusType" "PCI"
	Option "AccelMethod" "XAA"
EndSection

Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	Monitor    "Monitor0"
	DefaultDepth 24
	SubSection "Display"
		Viewport   0 0
		Virtual   3200 1200
		Modes     "1600x1200"
		Depth     24
	EndSubSection
EndSection

Section "Screen"
	Identifier "Screen2"
	Device     "Card2"
	Monitor    "Monitor2"
	DefaultDepth 24
	SubSection "Display"
		Viewport   0 0
		Virtual   1280 1024
		Modes     "1280x1024"
		Depth     24
	EndSubSection
EndSection
