# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 22 Nov 2008 06:46:09 -0500
*               @ALL          0
*               @user         8
