---
- name: Check if {{ default.nonroot_user }} exists
  shell: id -u {{ default.nonroot_user }}
  register: user_exists
  ignore_errors: true

- name: Create new user
  user:
    name: "{{ default.nonroot_user }}"
    password: "{{ default.nonroot_password }}"
    groups: "sudo"
    shell: "/bin/bash"
  when: user_exists != 0
