<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: faith
 * Date: Wed, 04 Jan 2012 12:21:32 -0500
 */

$conf['title'] = 'alephnull.com';
$conf['template'] = 'alephnull';
$conf['tocminheads'] = '0';
$conf['useacl'] = 1;
$conf['defaultgroup'] = 'guest';
$conf['superuser'] = '@admin';
$conf['registernotify'] = 'faith@alephnull.com';
$conf['disableactions'] = 'register';
$conf['sneaky_index'] = 1;
$conf['relnofollow'] = 0;
$conf['htmlok'] = 1;
$conf['subscribers'] = 1;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['xsendfile'] = '0';
$conf['spellchecker'] = '1';
$conf['tpl']['alephnull']['sidebar'] = 'both';
$conf['tpl']['alephnull']['left_sidebar_content'] = 'main,user,group';
$conf['tpl']['alephnull']['right_sidebar_content'] = 'user,group,namespace';
$conf['plugin']['captcha']['mode'] = 'image';
$conf['plugin']['discussion']['allowguests'] = '0';
$conf['savedir'] = '/www/alephnull.com/support/data';

// end auto-generated content
