---
- name: Install /etc/keymap.local
  copy:
    dest: /etc/keymap.local
    content: |
      keymaps 0-127
      keycode 58 = Control
      keycode 125 = grave
      shift keycode 125 = asciitilde
      keycode 41 = Escape
      keycode 29 = Alt

- name: Update /etc/rc.local
  blockinfile:
    dest: /etc/rc.local
    block: |
      loadkeys /etc/keymap.local
  when: using_ubuntu is undefined or using_ubuntu == False

- name: Update /etc/rc.local for Ubuntu
  copy:
    dest: /etc/rc.local
    mode: '0755'
    content: |
      #!/bin/bash
      loadkeys /etc/keymap.local
  when: using_ubuntu is defined and using_ubuntu == True

- name: Update /etc/sysctl.confa
  blockinfile:
    dest: /etc/sysctl.conf
    block: |
      kernel.dmesg_restrict=0
      fs.file-max=16384

- name: Update /etc/crontab
  blockinfile:
    dest: /etc/crontab
    block: |
      */10 *   * * * root logger "$(uptime)"

- name: Use anonymous ntp configuration
  copy:
    dest: /etc/ntpsec/ntp.conf
    content: |
      driftfile /var/lib/ntp/ntp.drift
      logfile /var/log/ntp.log
      leapfile /usr/share/zoneinfo/leap-seconds.list

      pool 0.debian.pool.ntp.org iburst
      pool 1.debian.pool.ntp.org iburst
      pool 2.debian.pool.ntp.org iburst
      pool 3.debian.pool.ntp.org iburst

      restrict -4 default kod notrap nomodify nopeer noquery limited
      restrict -6 default kod notrap nomodify nopeer noquery limited
      restrict 127.0.0.1
      restrict ::1

      restrict source notrap nomodify noquery
      disable monitor
      discard minimum 0
  when: ntp_anonymous is defined and ntp_anonymous == True

- name: Use local ntp configuration
  copy:
    dest: /etc/ntpsec/ntp.conf
    content: |
      driftfile /var/lib/ntp/ntp.drift
      logfile /var/log/ntp.log
      leapfile /usr/share/zoneinfo/leap-seconds.list

      statsdir /var/log/ntpstats/
      statistics loopstats peerstats clockstats
      filegen loopstats file loopstats type day enable
      filegen peerstats file peerstats type day enable
      filegen clockstats file clockstats type day enable

      server {{ ntp0 }} iburst
      server {{ ntp1 }} iburst
      server {{ ntp2 }} iburst
      server {{ ntp3 }} iburst
      server 127.127.1.0 # local clock

      restrict -4 default kod notrap nomodify nopeer noquery limited
      restrict -6 default kod notrap nomodify nopeer noquery limited
      restrict 127.0.0.1
      restrict ::1

      restrict source notrap nomodify noquery
      disable monitor
      discard minimum 0
  when: ntp_local is defined and ntp_local == True

