---
- name: Install /etc/keymap.local
  copy:
    dest: /etc/keymap.local
    content: |
      keymaps 0-127
      keycode 58 = Control
      keycode 125 = grave
      shift keycode 125 = asciitilde
      keycode 41 = Escape
      keycode 29 = Alt

- name: Update /etc/rc.local
  blockinfile:
    dest: /etc/rc.local
    block: |
      loadkeys /etc/keymap.local

- name: Update /etc/crontab
  blockinfile:
    dest: /etc/crontab
    block: |
      */10 *   * * * root logger "$(uptime)"

- name: Use anonymous ntp configuration
  copy:
    dest: /etc/ntpsec/ntp.conf
    content: |
      driftfile /var/lib/ntp/ntp.drift
      logfile /var/log/ntp.log
      leapfile /usr/share/zoneinfo/leap-seconds.list

      pool 0.debian.pool.ntp.org iburst
      pool 1.debian.pool.ntp.org iburst
      pool 2.debian.pool.ntp.org iburst
      pool 3.debian.pool.ntp.org iburst

      restrict -4 default kod notrap nomodify nopeer noquery limited
      restrict -6 default kod notrap nomodify nopeer noquery limited
      restrict 127.0.0.1
      restrict ::1

      restrict source notrap nomodify noquery
      disable monitor
      discard minimum 0
  when: ntp_anonymous is defined
