---

- name: Copy .ssh files
  copy:
    src: "/home/faith/.ssh/{{ item }}"
    dest: /home/faith/.ssh
    owner: faith
    group: faith
    mode: 0600
  with_items:
  - config
  - github
  - github.pub
  - gitlab
  - gitlab.pub
  - id_ed25519
  - id_ed25519.pub
  - lukem
  - lukem.pub
  - urwen
  - urwen.pub
  when: install_faith is defined and install_faith == True

- name: Checkout dotfiles2
  git:
    repo: 'git@rik.github.com:rikfaith/dotfiles2'
    dest: /home/faith/dotfiles2
    key_file: /home/faith/.ssh/github
    accept_hostkey: yes
  become: true
  become_user: faith
  when: install_faith is defined and install_faith == True

- name: Install dotfiles2
  command: "./bootstrap.py"
  become: true
  become_user: faith
  args:
    chdir: /home/faith/dotfiles2
  when: install_faith is defined and install_faith == True

- name: Use zsh
  user:
    name: faith
    shell: /bin/zsh
    create_home: no
  when: install_faith is defined and install_faith == True

- name: Activate zsh history
  file:
    path: /home/faith/.zhist
    state: touch
    mode: 0600
    owner: faith
    group: faith
  when: install_faith is defined and install_faith == True
