---
- include_tasks: update.yml
- include_tasks: sudo.yml
- include_tasks: systemd.yml
- include_tasks: bash.yml
- include_tasks: ssh.yml

- include_tasks: tools.yml
  when: not install_rpi

- include_tasks: files.yml
- include_tasks: local.yml

- name: Reboot
  reboot:
