---
- name: Force apt to use IPv4
  copy:
    dest: /etc/apt/apt.conf.d/99force-ipv4
    content: |
      Acquire::ForceIPv4 "true";

- name: Install gnupg
  apt:
    pkg: gnupg
    state: present
  when: using_devuan is defined

- name: Install devuan-keyring
  apt:
    pkg: devuan-keyring
    state: present
  when: using_devuan is defined

# This works around a bug when using update_cache: yes
- name: Update apt cache for current distribution
  command: apt-get update

- name: Upgrade current distribution
  apt:
    upgrade: dist
    update_cache: no
    autoremove: yes
  register: aptcurrent

- name: Reboot
  reboot:
  when: aptcurrent.changed

- name: Configure apt source for local sid
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://ftp.us.debian.org/debian/ sid main contrib non-free
      deb-src http://ftp.us.debian.org/debian/ sid main contrib non-free
  when: using_debian is defined

- name: Configure apt source for local ceres
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://deb.devuan.org/merged ceres main contrib non-free
      deb-src http://deb.devuan.org/merged ceres main contrib non-free
  when: using_devuan is defined

# This works around a bug when using update_cache: yes
- name: Update apt cache for unstable
  command: apt-get update

- name: Installing python-is-python3
  apt:
    pkg: python-is-python3
    update-cache: no
    autoremove: yes
  register: aptpython

- name: Upgrade to unstable (sid or ceres)
  apt:
    upgrade: dist
    update_cache: no
    autoremove: yes
  register: aptunstable

# We might have been using /usr/bin/python3.9 which was upgraded.
- name: Change python interpreter
  set_fact: discovered_interpreter_python="/usr/bin/python3"
  when: aptpython.changed

- name: Reboot
  reboot:
  when: aptpython.changed or aptunstable.changed

- name: Install (non-X11) tools
  apt:
    pkg:
      - alsa-utils
      - bc
      - bind9-utils
      - calibre
      - crypt++el
      - cryptsetup-bin
      - curl
      - dc
      - ddate
      - dmidecode
      - elpa-auto-complete
      - elpa-xcscope
      - emacs
      - git
      - htop
      - imagemagick
      - ipmitool
      - jnettop
      - lftp
      - libimage-exiftool-perl
      - libkf5wallet-bin
      - lm-sensors
      - lshw
      - lsscsi
      - lvm2
      - m4
      - mdadm
      - mediainfo
      - ncal
      - net-tools
      - nfs-common
      - nmap
      - ntpsec
      - ntpsec-ntpdate
      - parted
      - rsync
      - smartmontools
      - sysstat
      - tmux
      - units
      - unrar
      - unzip
      - vim
      - vnstat
      - whois
      - zsh

- name: Install virt tools
  apt:
    pkg:
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system
      - virtinst
      - virt-top
  when: install_virt_tools is defined

- name: Install X11 server
  apt:
    pkg:
      - xserver-xorg
  when: install_x11_tools is defined

- name: Install X11 intel driver
  apt:
    pkg:
      - xserver-xorg-video-intel
  when: install_intel_driver is defined

- name: Install X11 nvidia server
  apt:
    pkg:
      - xserver-xorg-video-nvidia
  when: install_nvidia_driver is defined

- name: Install X11 tools
  apt:
    pkg:
      - chromium
      - dclock
      - evince
      - firefox-esr
      - fvwm
      - ghostscript
      - gv
      - hexchat
      - mesa-utils
      - ssh-askpass-fullscreen
      - t1-xfree86-nonfree
      - telegram-desktop
      - ttf-xfree86-nonfree
      - vlc
      - x11-apps
      - x11-common
      - xfonts-100dpi
      - xfonts-100dpi-transcoded
      - xfonts-75dpi
      - xfonts-75dpi-transcoded
      - xfonts-terminus
      - xinit
      - xinput
      - xpdf
      - xterm
      - xtightvncviewer
  when: install_x11_tools is defined

- name: Install tools for openconnect
  apt:
    pkg:
      - python3-click
      - python3-keyring
      - python3-pip
      - python3-pyotp
  when: install_laptop_tools is defined

- name: Install laptop tools
  apt:
    pkg:
      - acpi
      - acpid
      - network-manager
      - openconnect
      - pm-utils
      - stalonetray
  when: install_laptop_tools is defined

- name: Upgrade current distribution (final upgrade)
  apt:
    upgrade: dist
    update_cache: no
    autoremove: yes
